SELECT DISTINCT PORT FROM 
(SELECT ORIGIN_PORT AS PORT FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026
UNION ALL 
SELECT DESTINATION_PORT AS PORT FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026
)
;

DESCRIBE TABLE KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026;

SELECT DISTINCT 
    ORIGIN_PORT
    , DESTINATION_PORT
    , FUEL_PRICE_INDEX
    , TRANSPORT_MODE
    , DISTANCE_KM
    , WEIGHT_MT
    , GEOPOLITICAL_RISK_SCORE
    , WEATHER_CONDITION
    , CARRIER_RELIABILITY_SCORE
    , DISRUPTION_OCCURRED
FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
SELECT 
    *
FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026 
WHERE DESTINATION_PORT='Rotterdam' 
AND ORIGIN_PORT = 'Antwerp' 
AND TRANSPORT_MODE = 'Air'
;

SELECT DISTINCT 
    weather_condition
FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026 
;
SELECT DISTINCT port 
FROM 
(SELECT 
    ORIGIN_PORT AS port 
FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026
UNION ALL 
SELECT 
    DESTINATION_PORT AS port 
FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026)
;

SELECT DISTINCT 
    DESTINATION_PORT
FROM KAGGLE_LOGISTICS.RAW.RAW_GLOBAL_SUPPLY_CHAIN_RISK_2026;