USE DATABASE KAGGLE_LOGISTICS;
DESCRIBE SCHEMA RAW;
DESCRIBE SCHEMA DEV_STAGING;
USE SCHEMA DEV_STAGING;
SELECT * FROM STG_DEV_SEEDS__CO2_EMISSION;
SELECT * FROM STG_DEV_SEEDS__DIM_TRANSPORT_FUEL;
SELECT * FROM STG_DEV_SEEDS__FCT_FUEL_PRICES;
SELECT * FROM STG_DEV_SEEDS__MAIN_PORTS;
SELECT * FROM STG_RAW__GLOBAL_SUPPLY_CHAIN_RISK_2024_2026;

DESCRIBE TABLE STG_RAW__GLOBAL_SUPPLY_CHAIN_RISK_2024_2026;
SELECT WEIGHT_MT FROM STG_RAW__GLOBAL_SUPPLY_CHAIN_RISK_2024_2026;
;

SELECT DISTINCT PORT FROM (
SELECT ORIGIN_PORT AS PORT FROM STG_RAW__GLOBAL_SUPPLY_CHAIN_RISK_2024_2026
UNION ALL 
SELECT DESTINATION_PORT AS PORT FROM STG_RAW__GLOBAL_SUPPLY_CHAIN_RISK_2024_2026
);

FROM 