-- CREATE TABLE FROM CSV FILE IN Staging 

CREATE FILE FORMAT GACHI_FILE_FORMAT 
TYPE = CSV 
PARSE_HEADER = TRUE 
;

CREATE OR REPLACE TABLE KAGGLE_LOGISTICS.RAW.GLOBAL_SUPPLY_CHAIN_RISK_2024_2026
USING TEMPLATE(
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@"KAGGLE_LOGISTICS"."RAW"."GLOBAL_SUPPLY_CHAIN_RISK_2024_2026"/global_supply_chain_risk_2026.csv',
            FILE_FORMAT => 'GACHI_FILE_FORMAT'
        )
    )
)
;

COPY INTO KAGGLE_LOGISTICS.RAW.GLOBAL_SUPPLY_CHAIN_RISK_2024_2026 
FROM '@"KAGGLE_LOGISTICS"."RAW"."GLOBAL_SUPPLY_CHAIN_RISK_2024_2026"/global_supply_chain_risk_2026.csv'
FILE_FORMAT = (FORMAT_NAME = 'GACHI_FILE_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
;